palette = "catppuccin_macchiato"
format = "$directory$character"
right_format = "$git_branch$git_commit$git_state$git_status$cmd_duration"
add_newline = true

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext0 = "#a5adce"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[directory]
style = "blue"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](mauve)"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "bold mauve"
truncation_length = 32
truncation_symbol = "…"

[git_commit]
commit_hash_length = 7
format = '[($hash$tag)]($style) '
style = "bold teal"
only_detached = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold pink"
conflicted = '≠${count}'
stashed = '≡${count}'
deleted = '✘${count}'
renamed = '»${count}'
modified = '●${count}'
typechanged = '~${count}'
staged = '+${count}'
untracked = '?${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
up_to_date = ""

[cmd_duration]
min_time = 2000
format = 'took [$duration]($style) '
style = "italic overlay1"
